// Code generated by cmd/cgo; DO NOT EDIT.

package gl

import "unsafe"

import _ "runtime/cgo"

import "syscall"

var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
type _Ctype_int int32

type _Ctype_uchar uint8

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
func _cgoCheckResult(interface{})

//go:cgo_import_static _cgo_7ada50ef5194_Cfunc_exit
//go:linkname __cgofn__cgo_7ada50ef5194_Cfunc_exit _cgo_7ada50ef5194_Cfunc_exit
var __cgofn__cgo_7ada50ef5194_Cfunc_exit byte
var _cgo_7ada50ef5194_Cfunc_exit = unsafe.Pointer(&__cgofn__cgo_7ada50ef5194_Cfunc_exit)

//go:cgo_unsafe_args
func _Cfunc_exit(p0 _Ctype_int) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_7ada50ef5194_Cfunc_exit, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_export_dynamic goStart
//go:linkname _cgoexp_7ada50ef5194_goStart _cgoexp_7ada50ef5194_goStart
//go:cgo_export_static _cgoexp_7ada50ef5194_goStart
func _cgoexp_7ada50ef5194_goStart(a *struct {
		p0 _Ctype_uchar
		p1 _Ctype_int
		p2 _Ctype_int
	}) {
goStart(a.p0, a.p1, a.p2)
}
